<a href="https://colab.research.google.com/github/Tradingmouse/public-computing-space/blob/main/arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [57]:
#comparison opperators  is used for mathmetics as example greater then or smaller then


import numpy as np
import pandas as pd
import math 

In [9]:
1 < 3

True

In [10]:
1 > 3

False

In [11]:
1 <= 3

True

In [12]:
1 == 1

True

In [13]:
1 != 1

False

In [14]:
"string" == 'string'

True

In [15]:
1 == "1"

False

In [16]:
#logic opperators

In [17]:
(1==3) and (1==1)

False

In [18]:
(1==3) or (1==1) 

True

In [19]:
(1==1) and not (1==2)  

True

In [20]:
#el if elif statement = controleflow 

In [21]:
if True:
  print ("hello world")

hello world


In [22]:
if False:
  print ("hello world")

In [23]:
if (1==1):
  print ("hello darkness my old friend")

hello darkness my old friend


In [24]:
if (1==2):
  print ("hello darkness my old friend")

In [26]:
import math 

In [25]:
print(math.sqrt(300))  

17.320508075688775


In [27]:
import numpy as np

In [28]:
my_list = [1,2,3]

In [29]:
x = np.array(my_list)

type (x)

numpy.ndarray

In [30]:
my_matrix = [[1,2,3], [4,5,6],[7,8,9]]

In [31]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
list(range(0,5))
np.arange(0,5)


array([0, 1, 2, 3, 4])

In [33]:
np.arange (0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
type(1)
type (1.0)

float

In [35]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [45]:
np.random.rand(5)

array([0.90891198, 0.5020986 , 0.83022693, 0.66437504, 0.99799393])

In [37]:
np.random.rand(5,4) # every number have eq chance to get picked

array([[0.293222  , 0.9475962 , 0.01716362, 0.86331049],
       [0.77029962, 0.78882469, 0.02644195, 0.36759073],
       [0.08362796, 0.00981111, 0.27448345, 0.49919115],
       [0.42546   , 0.75423991, 0.03129975, 0.52432814],
       [0.80360578, 0.76637269, 0.56578885, 0.44922255]])

In [38]:
np.random.randn(5,3)

array([[-0.34123807, -1.80073379,  0.91005859],
       [ 0.58986773,  1.40820233,  0.47904   ],
       [-1.45138245, -0.03561151,  0.44593647],
       [ 0.59337436,  0.6232731 , -2.13787281],
       [-0.75217794,  0.98002954,  0.07304664]])

In [42]:
np.random.randint(0,100)


4

In [41]:
np.array.reshape(5,6)

AttributeError: ignored

In [48]:
np.exp(arr)

NameError: ignored

In [52]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [55]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [56]:
np.ones((420,69))

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [58]:
np.eye(4)  

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [64]:
np.random.rand(5,4)


array([[0.10343401, 0.42626788, 0.1097547 , 0.91936652],
       [0.44614808, 0.3777663 , 0.63293121, 0.24657868],
       [0.22837768, 0.90125672, 0.55145069, 0.90332157],
       [0.74304562, 0.19163071, 0.64859396, 0.74562445],
       [0.23549293, 0.61136845, 0.33123051, 0.24742795]])

In [65]:
np.random.randn(5,4)

array([[-1.30401018, -1.02835637,  0.83768615, -0.33758915],
       [-0.02606147,  1.07679394,  1.53144576,  1.21759723],
       [ 0.94961956,  0.42418054, -1.05224168,  0.96923842],
       [-0.43752112,  0.33645998,  0.43271918,  1.31464173],
       [ 0.51561105, -0.32614081,  0.91936904, -1.7055861 ]])

In [70]:
ranarr.agrim()

NameError: ignored

In [73]:
np.max(np.array)
arr.max()

NameError: ignored